openapi: "3.0.0"
info:
  version: 1.0.0
  title: AP 2018 Bookstore
paths:
  /books:
    get:
      summary: List books
      operationId: listBooks
      responses:
        '200':
          description: An array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
components:
  schemas:
    Book:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
        tag:
          type: string
        pages:
          type: integer
          format: int64
